package com.khamphaviet.restaurant.billing;
import com.khamphaviet.restaurant.common.BusinessException;import com.khamphaviet.restaurant.order.*;import com.khamphaviet.restaurant.reservation.*;import com.khamphaviet.restaurant.service.*;import com.khamphaviet.restaurant.table.RestaurantTableRepository;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.util.*;
@Service public class CheckoutService{
 private static final List<DiningOrderStatus> OPEN=List.of(DiningOrderStatus.SUBMITTED,DiningOrderStatus.PREPARING,DiningOrderStatus.READY);
 private final ServiceSessionRepository sessions;private final ReservationRepository reservations;private final ReservationTableAssignmentRepository assignments;private final RestaurantTableRepository tables;private final DiningOrderRepository orders;private final DiningOrderItemRepository items;private final PaymentRepository payments;
 public CheckoutService(ServiceSessionRepository sessions,ReservationRepository reservations,ReservationTableAssignmentRepository assignments,RestaurantTableRepository tables,DiningOrderRepository orders,DiningOrderItemRepository items,PaymentRepository payments){this.sessions=sessions;this.reservations=reservations;this.assignments=assignments;this.tables=tables;this.orders=orders;this.items=items;this.payments=payments;}
 public List<CheckoutDtos.Checkout> list(){return sessions.findByStatus(ServiceSessionStatus.ACTIVE).stream().map(this::response).toList();}
 @Transactional public CheckoutDtos.Checkout pay(Long sessionId,CheckoutDtos.PayRequest request){ServiceSession session=sessions.findById(sessionId).filter(s->s.getStatus()==ServiceSessionStatus.ACTIVE).orElseThrow(()->new BusinessException("Phiên phục vụ không còn hoạt động"));if(payments.findByServiceSessionId(sessionId).isPresent())throw new BusinessException("Hóa đơn này đã được thanh toán");long open=orders.countByServiceSessionIdAndStatusIn(sessionId,OPEN);if(open>0)throw new BusinessException("Còn "+open+" phiếu món chưa phục vụ");BigDecimal subtotal=subtotal(sessionId);if(request.discountAmount().compareTo(subtotal)>0)throw new BusinessException("Tiền giảm giá không được lớn hơn tổng tiền món");payments.save(new Payment(sessionId,subtotal,request.discountAmount(),request.method()));return response(session);}
 private BigDecimal subtotal(Long sessionId){List<DiningOrder> served=orders.findByServiceSessionIdOrderByCreatedAtDesc(sessionId).stream().filter(o->o.getStatus()==DiningOrderStatus.SERVED).toList();if(served.isEmpty())return BigDecimal.ZERO;return items.findByOrderIdInOrderByIdAsc(served.stream().map(DiningOrder::getId).toList()).stream().map(i->i.getUnitPrice().multiply(BigDecimal.valueOf(i.getQuantity()))).reduce(BigDecimal.ZERO,BigDecimal::add);}
 private CheckoutDtos.Checkout response(ServiceSession session){Reservation r=reservations.findById(session.getReservationId()).orElseThrow();List<DiningOrder> served=orders.findByServiceSessionIdOrderByCreatedAtDesc(session.getId()).stream().filter(o->o.getStatus()==DiningOrderStatus.SERVED).toList();List<DiningOrderItem> detail=served.isEmpty()?List.of():items.findByOrderIdInOrderByIdAsc(served.stream().map(DiningOrder::getId).toList());List<CheckoutDtos.Line> lines=detail.stream().map(i->new CheckoutDtos.Line(i.getItemNameSnapshot(),i.getQuantity(),i.getUnitPrice(),i.getUnitPrice().multiply(BigDecimal.valueOf(i.getQuantity())))).toList();BigDecimal subtotal=lines.stream().map(CheckoutDtos.Line::lineTotal).reduce(BigDecimal.ZERO,BigDecimal::add);List<String> tableCodes=tables.findAllById(assignments.findByReservationId(r.getId()).stream().map(ReservationTableAssignment::getTableId).toList()).stream().map(t->t.getCode()).sorted().toList();long open=orders.countByServiceSessionIdAndStatusIn(session.getId(),OPEN);Payment p=payments.findByServiceSessionId(session.getId()).orElse(null);return new CheckoutDtos.Checkout(session.getId(),r.getId(),r.getCode(),r.getCustomerName(),tableCodes,r.getPartySize(),lines,subtotal,open,p!=null,p==null?null:p.getId(),p==null?null:p.getInvoiceCode(),p==null?BigDecimal.ZERO:p.getDiscountAmount(),p==null?subtotal:p.getTotalAmount(),p==null?null:p.getMethod(),p==null?null:p.getPaidAt());}
}
