package com.khamphaviet.restaurant.demo;

public enum DemoScenarioType {
    WALK_IN_NORMAL,
    WALK_IN_WARNING,
    WALK_IN_CRITICAL,
    RESERVATION_NEW,
    RESERVATION_UPCOMING,
    RESERVATION_LATE_WARNING,
    RESERVATION_LATE_CRITICAL,
    RESERVATION_HOLD_EXPIRED,
    RESERVATION_DEPOSIT_WAITING,
    KITCHEN_NEW_ORDER,
    KITCHEN_PREPARING,
    KITCHEN_REPORTED_DELAY,
    KITCHEN_OVERDUE_WARNING,
    KITCHEN_OVERDUE_CRITICAL,
    KITCHEN_READY,
    QR_CALL_WAITER,
    QR_WATER,
    QR_PAYMENT,
    QR_UNANSWERED_WARNING,
    QR_UNANSWERED_CRITICAL,
    TABLE_CLEANING_NORMAL,
    TABLE_CLEANING_WARNING,
    TABLE_CLEANING_CRITICAL
}
