ALTER TABLE operational_timeouts ADD COLUMN assigned_to VARCHAR(180);
ALTER TABLE operational_timeouts ADD COLUMN assigned_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE operational_timeouts ADD COLUMN acknowledged_by VARCHAR(180);
ALTER TABLE operational_timeouts ADD COLUMN acknowledged_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE operational_timeouts ADD COLUMN resolved_by VARCHAR(180);

CREATE TABLE operational_timeout_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timeout_id BIGINT NOT NULL,
    action VARCHAR(40) NOT NULL,
    actor VARCHAR(180) NOT NULL,
    from_assignee VARCHAR(180),
    to_assignee VARCHAR(180),
    note VARCHAR(400),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_timeout_event_timeout FOREIGN KEY (timeout_id) REFERENCES operational_timeouts(id)
);

CREATE INDEX idx_timeout_events_timeout_created
    ON operational_timeout_events(timeout_id, created_at DESC);
CREATE UNIQUE INDEX ux_payment_provider_capture
    ON payments(provider_capture_id) WHERE provider_capture_id IS NOT NULL;
