package com.khamphaviet.restaurant.notification;
public enum NotificationType { NEW_RESERVATION, DEPOSIT_PAID, RESERVATION_CONFIRMED, UPCOMING_30, LATE_15, LATE_20, TABLE_CALL, KITCHEN_DELAY, DISH_READY, WALK_IN, WALK_IN_TIMEOUT, TIMEOUT }
