import{useEffect,useMemo,useState}from'react';
import{Armchair,Check,CheckCircle2,ChevronDown,LogIn,ShoppingBasket,Sparkles,Users,X}from'lucide-react';
import{api}from'../api';
import type{Reservation,RestaurantTable}from'../types';
import{Link}from'react-router-dom';

export default function DashboardPage(){
  const[rows,setRows]=useState<Reservation[]>([]);const[tables,setTables]=useState<RestaurantTable[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState<number|null>(null);
  const load=async()=>{try{const[reservations,restaurantTables]=await Promise.all([api.staffReservations(),api.tables()]);setRows(reservations);setTables(restaurantTables);setError('')}catch(e){setError(e instanceof Error?e.message:'Không tải được dữ liệu')}};
  useEffect(()=>{void load()},[]);
  async function action(id:number,operation:()=>Promise<unknown>){setBusy(id);setError('');try{await operation();await load()}catch(e){setError(e instanceof Error?e.message:'Không thực hiện được thao tác')}finally{setBusy(null)}}
  const active=rows.filter(r=>!['COMPLETED','CANCELLED','REJECTED','NO_SHOW'].includes(r.status));
  return <section className="dashboard page-section container"><p className="eyebrow dark">VẬN HÀNH NHÀ HÀNG</p><h1>Quản lý đặt bàn</h1><div className="stats"><div><b>{active.length}</b><span>Đơn đang hoạt động</span></div><div><b>{rows.filter(x=>x.status==='PENDING').length}</b><span>Chờ xác nhận</span></div><div><b>{rows.filter(x=>x.status==='CHECKED_IN').length}</b><span>Đang phục vụ</span></div><div><b>{tables.filter(t=>t.status==='AVAILABLE').length}</b><span>Bàn đang trống</span></div></div>{error&&<p className="error">{error}</p>}<div className="table-wrap"><table className="reservation-table service-table"><thead><tr><th>Mã & khách hàng</th><th>Lịch</th><th>Món chọn trước</th><th>Xếp bàn</th><th>Trạng thái & phục vụ</th></tr></thead><tbody>{rows.map(reservation=><tr key={reservation.id}><td><b>{reservation.code}</b><span className="reservation-name">{reservation.customerName}</span><small>{reservation.phone} • {reservation.partySize} khách</small></td><td>{reservation.reservationDate}<small>{reservation.timeSlot==='LUNCH'?'Bữa trưa':'Bữa tối'}</small></td><td><PreOrder reservation={reservation} busy={busy===reservation.id} onConfirm={()=>action(reservation.id,()=>api.confirmPreOrder(reservation.id))}/></td><td><TableAssignment reservation={reservation} tables={tables} busy={busy===reservation.id} onAssign={ids=>action(reservation.id,()=>api.assignTables(reservation.id,ids))}/></td><td><ServiceActions reservation={reservation} busy={busy===reservation.id} onStatus={status=>action(reservation.id,()=>api.updateStatus(reservation.id,status))} onCheckIn={()=>action(reservation.id,()=>api.checkIn(reservation.id))} onComplete={()=>action(reservation.id,()=>api.completeService(reservation.id))}/></td></tr>)}</tbody></table>{!rows.length&&!error&&<p className="empty">Chưa có đơn đặt bàn.</p>}</div><p className="security-note">Quy trình chuẩn: xác nhận đơn → xếp đủ bàn → check-in → phục vụ → hoàn tất và dọn bàn.</p></section>;
}

function PreOrder({reservation,busy,onConfirm}:{reservation:Reservation;busy:boolean;onConfirm:()=>void}){const requested=reservation.preOrderItems?.some(item=>item.status==='REQUESTED');if(!reservation.preOrderItems?.length)return <span className="no-preorder">Không chọn trước</span>;return <div className="staff-preorder"><div className="staff-preorder-title"><ShoppingBasket/><b>{reservation.preOrderItems.reduce((sum,item)=>sum+item.quantity,0)} phần</b><span className={requested?'requested':'confirmed'}>{requested?'Chờ xác nhận':'Đã xác nhận'}</span></div><ul>{reservation.preOrderItems.map(item=><li key={item.id}><span>{item.quantity}× {item.itemName}</span><b>{Number(item.lineTotal).toLocaleString('vi-VN')}đ</b></li>)}</ul>{requested&&<button disabled={busy} onClick={onConfirm}><Check/> Xác nhận món với khách</button>}</div>}

function TableAssignment({reservation,tables,busy,onAssign}:{reservation:Reservation;tables:RestaurantTable[];busy:boolean;onAssign:(ids:number[])=>void}){
  const[open,setOpen]=useState(false);const[selected,setSelected]=useState<number[]>(reservation.assignedTables?.map(t=>t.id)||[]);
  useEffect(()=>setSelected(reservation.assignedTables?.map(t=>t.id)||[]),[reservation.assignedTables]);
  const currentIds=new Set(reservation.assignedTables?.map(t=>t.id)||[]);const available=tables.filter(t=>t.active&&(t.status==='AVAILABLE'||currentIds.has(t.id)));const capacity=available.filter(t=>selected.includes(t.id)).reduce((sum,t)=>sum+t.seats,0);
  const locked=['CHECKED_IN','COMPLETED','CANCELLED','REJECTED'].includes(reservation.status);
  function toggle(id:number){setSelected(value=>value.includes(id)?value.filter(item=>item!==id):[...value,id])}
  return <div className="assignment"><div className="assigned-list">{reservation.assignedTables?.length?reservation.assignedTables.map(table=><span key={table.id}><Armchair/>{table.code}<small>{table.seats} ghế</small></span>):<i>Chưa xếp bàn</i>}</div>{!locked&&<button className="assignment-toggle" onClick={()=>setOpen(!open)}><Armchair/> {reservation.assignedTables?.length?'Đổi bàn':'Xếp bàn'} <ChevronDown/></button>}{open&&<div className="assignment-panel"><div className="assignment-panel-head"><b>Chọn bàn cho {reservation.partySize} khách</b><button onClick={()=>setOpen(false)}><X/></button></div><div className={`capacity-check ${capacity>=reservation.partySize?'enough':''}`}><Users/><span>Đã chọn {capacity}/{reservation.partySize} ghế</span></div><div className="assignment-options">{available.map(table=><label className={selected.includes(table.id)?'selected':''} key={table.id}><input type="checkbox" checked={selected.includes(table.id)} onChange={()=>toggle(table.id)}/><span><b>{table.code}</b><small>{table.floor} • {table.area}</small></span><strong>{table.seats} ghế</strong></label>)}</div><button className="save-assignment" disabled={busy||capacity<reservation.partySize} onClick={()=>{onAssign(selected);setOpen(false)}}><Check/> Lưu xếp bàn</button></div>}</div>
}

function ServiceActions({reservation,busy,onStatus,onCheckIn,onComplete}:{reservation:Reservation;busy:boolean;onStatus:(status:string)=>void;onCheckIn:()=>void;onComplete:()=>void}){
  if(reservation.status==='PENDING')return <div className="service-actions"><span className="flow-status pending">Chờ xác nhận</span><button disabled={busy} className="confirm-reservation" onClick={()=>onStatus('CONFIRMED')}><CheckCircle2/> Xác nhận đơn</button><button disabled={busy} className="reject-reservation" onClick={()=>onStatus('REJECTED')}>Từ chối</button></div>;
  if(reservation.status==='CONFIRMED')return <div className="service-actions"><span className="flow-status confirmed">Đã xác nhận</span><button disabled={busy||!reservation.assignedTables?.length} className="checkin" onClick={onCheckIn}><LogIn/> Check-in khách</button><button disabled={busy} className="reject-reservation" onClick={()=>onStatus('CANCELLED')}>Hủy đơn</button>{!reservation.assignedTables?.length&&<small>Cần xếp bàn trước</small>}</div>;
  if(reservation.status==='CHECKED_IN')return <div className="service-actions"><span className="flow-status serving">Đang phục vụ</span><small>Phiên #{reservation.serviceSessionId}</small><Link className="order-link" to="/staff/phuc-vu"><ShoppingBasket/> {reservation.openOrderCount>0?`Xử lý ${reservation.openOrderCount} phiếu món`:'Gọi món'}</Link><button disabled={busy||reservation.openOrderCount>0||!reservation.paid} className="complete-service" onClick={onComplete}><Sparkles/> Hoàn tất lượt khách</button>{reservation.openOrderCount>0?<small className="open-order-warning">Còn món chưa phục vụ</small>:!reservation.paid?<small className="open-order-warning">Đang chờ thu ngân thanh toán</small>:<small>Hóa đơn đã thanh toán</small>}</div>;
  return <div className="service-actions"><span className={`flow-status ${reservation.status.toLowerCase()}`}>{reservation.status==='COMPLETED'?'Hoàn thành':reservation.status==='CANCELLED'?'Đã hủy':reservation.status==='REJECTED'?'Đã từ chối':reservation.status}</span></div>;
}
