import{useEffect,useState}from'react';
import{Check,ShoppingBasket}from'lucide-react';
import{api}from'../api';
import type{Reservation}from'../types';

const statuses=['PENDING','CONFIRMED','CHECKED_IN','COMPLETED','CANCELLED','REJECTED','NO_SHOW'];

export default function DashboardPage(){
  const[rows,setRows]=useState<Reservation[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState<number|null>(null);
  const load=()=>api.staffReservations().then(setRows).catch(e=>setError(e.message));
  useEffect(()=>{void load()},[]);
  async function update(id:number,status:string){setBusy(id);try{await api.updateStatus(id,status);await load()}catch(e){setError(e instanceof Error?e.message:'Không cập nhật được')}finally{setBusy(null)}}
  async function confirmItems(id:number){setBusy(id);try{await api.confirmPreOrder(id);await load()}catch(e){setError(e instanceof Error?e.message:'Không xác nhận được món')}finally{setBusy(null)}}
  return <section className="dashboard page-section container"><p className="eyebrow dark">VẬN HÀNH NHÀ HÀNG</p><h1>Quản lý đặt bàn</h1><div className="stats"><div><b>{rows.length}</b><span>Tổng đơn</span></div><div><b>{rows.filter(x=>x.status==='PENDING').length}</b><span>Chờ xác nhận</span></div><div><b>{rows.filter(x=>x.status==='CONFIRMED').length}</b><span>Đã xác nhận</span></div><div><b>{rows.reduce((n,x)=>n+x.partySize,0)}</b><span>Lượt khách</span></div></div>{error&&<p className="error">{error}</p>}<div className="table-wrap"><table className="reservation-table"><thead><tr><th>Mã</th><th>Khách hàng</th><th>Lịch</th><th>Số khách</th><th>Món chọn trước</th><th>Trạng thái bàn</th></tr></thead><tbody>{rows.map(reservation=>{const requested=reservation.preOrderItems?.some(item=>item.status==='REQUESTED');return <tr key={reservation.id}><td><b>{reservation.code}</b></td><td>{reservation.customerName}<small>{reservation.phone}</small></td><td>{reservation.reservationDate}<small>{reservation.timeSlot==='LUNCH'?'Bữa trưa':'Bữa tối'}</small></td><td>{reservation.partySize}</td><td>{reservation.preOrderItems?.length?<div className="staff-preorder"><div className="staff-preorder-title"><ShoppingBasket/><b>{reservation.preOrderItems.reduce((sum,item)=>sum+item.quantity,0)} phần</b><span className={requested?'requested':'confirmed'}>{requested?'Chờ xác nhận':'Đã xác nhận'}</span></div><ul>{reservation.preOrderItems.map(item=><li key={item.id}><span>{item.quantity}× {item.itemName}</span><b>{Number(item.lineTotal).toLocaleString('vi-VN')}đ</b></li>)}</ul>{requested&&<button disabled={busy===reservation.id} onClick={()=>confirmItems(reservation.id)}><Check/> Xác nhận món với khách</button>}</div>:<span className="no-preorder">Không chọn trước</span>}</td><td><select disabled={busy===reservation.id} value={reservation.status} onChange={e=>update(reservation.id,e.target.value)}>{statuses.map(status=><option key={status}>{status}</option>)}</select></td></tr>})}</tbody></table>{!rows.length&&!error&&<p className="empty">Chưa có đơn đặt bàn.</p>}</div><p className="security-note">Món khách chọn trước chỉ chuyển sang “Đã xác nhận” sau khi nhân viên trao đổi lại với khách.</p></section>;
}
