import{FormEvent,useEffect,useMemo,useState}from'react';
import{CheckCircle2,Minus,Plus,Search,ShoppingBasket}from'lucide-react';
import{api}from'../api';
import type{MenuItem,Reservation}from'../types';

const initial={customerName:'',phone:'',email:'',reservationDate:'',timeSlot:'DINNER',partySize:2,preferredFloor:'NO_PREFERENCE',note:''};

export default function ReservationPage(){
  const[form,setForm]=useState(initial);const[result,setResult]=useState<Reservation|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(false);
  const[menu,setMenu]=useState<MenuItem[]>([]);const[quantities,setQuantities]=useState<Record<number,number>>({});const[category,setCategory]=useState('Tất cả');const[search,setSearch]=useState('');
  useEffect(()=>{api.menu().then(setMenu).catch(()=>setError('Không tải được thực đơn'))},[]);
  const categories=useMemo(()=>['Tất cả',...new Set(menu.map(item=>item.category))],[menu]);
  const shown=useMemo(()=>menu.filter(item=>(category==='Tất cả'||item.category===category)&&item.name.toLowerCase().includes(search.toLowerCase())),[menu,category,search]);
  const selectedItems=menu.filter(item=>(quantities[item.id]||0)>0);
  const selectedCount=selectedItems.reduce((sum,item)=>sum+(quantities[item.id]||0),0);
  const estimatedTotal=selectedItems.reduce((sum,item)=>sum+Number(item.price)*(quantities[item.id]||0),0);
  const change=(key:string,value:string|number)=>setForm({...form,[key]:value});
  const changeQty=(id:number,delta:number)=>setQuantities(current=>({...current,[id]:Math.max(0,Math.min(20,(current[id]||0)+delta))}));
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');try{const preOrderItems=selectedItems.map(item=>({menuItemId:item.id,quantity:quantities[item.id]}));setResult(await api.createReservation({...form,preOrderItems}))}catch(err){setError(err instanceof Error?err.message:'Không thể đặt bàn')}finally{setLoading(false)}}

  if(result)return <section className="success-card"><CheckCircle2/><p className="eyebrow dark">YÊU CẦU ĐÃ ĐƯỢC GỬI</p><h1>Cảm ơn {result.customerName}!</h1><p>Mã đặt bàn của bạn là</p><strong>{result.code}</strong>{result.preOrderItems.length>0&&<div className="success-preorder"><ShoppingBasket/><b>{result.preOrderItems.reduce((sum,item)=>sum+item.quantity,0)} phần món đang chờ nhân viên xác nhận</b><span>Nhà hàng sẽ trao đổi lại với bạn khi xác nhận đặt bàn.</span></div>}<p>Nhà hàng sẽ liên hệ xác nhận. Hãy lưu mã này cùng số điện thoại để tra cứu.</p></section>;

  return <section className="reservation-layout"><div className="reservation-story"><div><p className="eyebrow">ĐẶT BÀN TRỰC TUYẾN</p><h1>Sẵn sàng cho một<br/>bữa ăn đáng nhớ?</h1><p>Chọn ngày, ca phục vụ, số khách và món ăn muốn dùng trước. Nhân viên sẽ xác nhận lại toàn bộ yêu cầu.</p><ul><li>Ca trưa bắt đầu từ 11:00</li><li>Ca tối bắt đầu từ 17:30</li><li>Món chọn trước chưa phải đơn gọi món chính thức</li></ul></div></div><form className="reservation-form" onSubmit={submit}><p className="eyebrow dark">THÔNG TIN ĐẶT BÀN</p><h2>Giữ chỗ của bạn</h2><div className="form-grid"><label>Họ và tên<input required value={form.customerName} onChange={e=>change('customerName',e.target.value)} placeholder="Nguyễn Văn An"/></label><label>Số điện thoại<input required value={form.phone} onChange={e=>change('phone',e.target.value)} placeholder="0984 353 577"/></label><label>Email<input type="email" value={form.email} onChange={e=>change('email',e.target.value)} placeholder="ban@example.com"/></label><label>Ngày dùng bữa<input required type="date" min={new Date().toISOString().slice(0,10)} value={form.reservationDate} onChange={e=>change('reservationDate',e.target.value)}/></label><label>Ca phục vụ<select value={form.timeSlot} onChange={e=>change('timeSlot',e.target.value)}><option value="LUNCH">Bữa trưa — 11:00</option><option value="DINNER">Bữa tối — 17:30</option></select></label><label>Số khách<input required type="number" min="1" max="300" value={form.partySize} onChange={e=>change('partySize',Number(e.target.value))}/></label><label>Tầng mong muốn<select value={form.preferredFloor} onChange={e=>change('preferredFloor',e.target.value)}><option value="NO_PREFERENCE">Không yêu cầu</option><option value="FLOOR_1">Tầng 1 — 120 ghế</option><option value="FLOOR_2">Tầng 2 — 180 ghế</option></select></label><label className="wide">Ghi chú<textarea value={form.note} onChange={e=>change('note',e.target.value)} placeholder="Sinh nhật, ăn chay, ghế trẻ em..."/></label></div>
  <div className="preorder-section"><div className="preorder-heading"><div><p className="eyebrow dark">KHÔNG BẮT BUỘC</p><h2>Chọn món trước</h2><p>Nhân viên sẽ kiểm tra và xác nhận lại món, số lượng và giá với bạn.</p></div><div className="preorder-total"><ShoppingBasket/><span><b>{selectedCount} phần</b><small>Tạm tính {estimatedTotal.toLocaleString('vi-VN')}đ</small></span></div></div><div className="preorder-tools"><div><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm món..."/></div><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(item=><option key={item}>{item}</option>)}</select></div><div className="preorder-grid">{shown.map(item=><article className={(quantities[item.id]||0)>0?'selected':''} key={item.id}><img src={item.imageUrl} alt={item.name}/><div><span>{item.category}</span><h3>{item.name}</h3><b>{Number(item.price).toLocaleString('vi-VN')}đ</b></div><div className="quantity"><button type="button" aria-label={`Giảm ${item.name}`} onClick={()=>changeQty(item.id,-1)}><Minus/></button><strong>{quantities[item.id]||0}</strong><button type="button" aria-label={`Thêm ${item.name}`} onClick={()=>changeQty(item.id,1)}><Plus/></button></div></article>)}</div></div>
  {error&&<p className="error">{error}</p>}<button disabled={loading} className="btn btn-green">{loading?'Đang gửi...':`Gửi yêu cầu đặt bàn${selectedCount?` • ${selectedCount} phần món`:''}`}</button></form></section>;
}
