import{FormEvent,useEffect,useMemo,useState}from'react';
import{Armchair,Bell,CheckCircle2,Clock3,Mail,Minus,Plus,ShoppingBasket}from'lucide-react';
import{api}from'../api';
import type{AvailableTable,MenuItem,Reservation}from'../types';
import DepositPayment from'../components/DepositPayment';

const initial={customerName:'',phone:'',email:'',reservationDate:'',timeSlot:'DINNER',reservationTime:'18:00',durationMinutes:120,partySize:2,note:'',notifyEmail:true,notifySms:true};

export default function ReservationPage(){
  const[form,setForm]=useState(initial);const[result,setResult]=useState<Reservation>();const[menu,setMenu]=useState<MenuItem[]>([]);
  const[tables,setTables]=useState<AvailableTable[]>([]);const[selectedTables,setSelectedTables]=useState<number[]>([]);
  const[qty,setQty]=useState<Record<number,number>>({});const[error,setError]=useState('');const[loading,setLoading]=useState(false);
  useEffect(()=>{api.menu().then(setMenu).catch(()=>setError('Không tải được thực đơn'))},[]);
  useEffect(()=>{if(!form.reservationDate||!form.reservationTime)return;const timer=setTimeout(()=>api.availableTables(form.reservationDate,form.reservationTime,form.durationMinutes,form.partySize).then(data=>{setTables(data);setSelectedTables(ids=>ids.filter(id=>data.some(t=>t.id===id)))}).catch(e=>setError(e instanceof Error?e.message:'Không tải được sơ đồ bàn')),250);return()=>clearTimeout(timer)},[form.reservationDate,form.reservationTime,form.durationMinutes,form.partySize]);
  const selected=menu.filter(x=>(qty[x.id]||0)>0);const total=selected.reduce((s,x)=>s+Number(x.price)*(qty[x.id]||0),0);const deposit=selected.length?Math.round(total*.1):200000*Number(form.partySize);
  const capacity=useMemo(()=>tables.filter(t=>selectedTables.includes(t.id)).reduce((sum,t)=>sum+t.seats,0),[tables,selectedTables]);
  const change=(key:string,value:string|number|boolean)=>setForm({...form,[key]:value});
  function toggleTable(id:number){setSelectedTables(value=>value.includes(id)?value.filter(x=>x!==id):[...value,id])}
  async function submit(e:FormEvent){e.preventDefault();if(!selectedTables.length||capacity<form.partySize){setError('Hãy chọn bàn có đủ ghế cho đoàn khách');return}setLoading(true);setError('');try{setResult(await api.createReservation({...form,preferredFloor:'GROUND_FLOOR',selectedTableIds:selectedTables,preOrderItems:selected.map(x=>({menuItemId:x.id,quantity:qty[x.id]}))}))}catch(e){setError(e instanceof Error?e.message:'Không thể đặt bàn')}finally{setLoading(false)}}
  if(result)return <section className="success-card deposit-success"><CheckCircle2/><p className="eyebrow dark">YÊU CẦU ĐÃ ĐƯỢC GỬI</p><h1>Cảm ơn {result.customerName}!</h1><p>Mã đặt bàn của bạn</p><strong>{result.code}</strong><p><Clock3/> {result.reservationDate} lúc {result.reservationTime} · {result.durationMinutes} phút</p><p><Armchair/> {result.assignedTables.map(t=>t.code).join(', ')}</p><div className="deposit-summary"><span>Tiền đặt cọc</span><b>{Number(result.depositAmount).toLocaleString('vi-VN')} ₫</b><small>Bàn được giữ 10 phút trong khi chờ thanh toán</small></div>{result.depositStatus==='PAID'?<div className="deposit-paid"><CheckCircle2/>Đã thanh toán bằng {result.depositMethod}</div>:<DepositPayment code={result.code} phone={result.phone} amount={result.depositAmount} onPaid={()=>setResult({...result,depositStatus:'PAID'})}/>}</section>;
  return <section className="reservation-layout"><div className="reservation-story"><div><p className="eyebrow">ĐẶT BÀN THEO GIỜ</p><h1>Chọn đúng bàn,<br/>đúng thời gian.</h1><p>Hệ thống giữ bàn 10 phút khi chờ đặt cọc và tự cộng 15 phút dọn bàn để tránh trùng lịch.</p></div></div><form className="reservation-form" onSubmit={submit}><p className="eyebrow dark">THÔNG TIN ĐẶT BÀN</p><h2>Giữ chỗ của bạn</h2><div className="form-grid"><label>Họ và tên<input required value={form.customerName} onChange={e=>change('customerName',e.target.value)}/></label><label>Số điện thoại<input required value={form.phone} onChange={e=>change('phone',e.target.value)}/></label><label>Email<input type="email" value={form.email} onChange={e=>change('email',e.target.value)}/></label><label>Ngày dùng bữa<input required type="date" min={new Date().toISOString().slice(0,10)} value={form.reservationDate} onChange={e=>change('reservationDate',e.target.value)}/></label><label>Giờ đến<input required type="time" min="10:00" max="21:30" step="900" value={form.reservationTime} onChange={e=>{change('reservationTime',e.target.value);setForm(v=>({...v,reservationTime:e.target.value,timeSlot:e.target.value<'15:00'?'LUNCH':'DINNER'}))}}/></label><label>Thời lượng<select value={form.durationMinutes} onChange={e=>change('durationMinutes',Number(e.target.value))}><option value={90}>90 phút</option><option value={120}>120 phút</option><option value={150}>150 phút</option><option value={180}>180 phút</option></select></label><label>Số khách<input required type="number" min="1" max="30" value={form.partySize} onChange={e=>change('partySize',Number(e.target.value))}/></label><label className="wide">Ghi chú<textarea value={form.note} onChange={e=>change('note',e.target.value)}/></label></div>
    <div className="notification-preferences"><h3><Bell/> Nhận nhắc lịch</h3><label><input type="checkbox" checked={form.notifySms} onChange={e=>change('notifySms',e.target.checked)}/> SMS đến số điện thoại</label><label><input type="checkbox" checked={form.notifyEmail} disabled={!form.email} onChange={e=>change('notifyEmail',e.target.checked)}/><Mail/> Gmail/email</label><small>Nhắc trước 30 phút và khi trễ 15–20 phút. SMS đang chạy Sandbox trong đồ án.</small></div>
    <div className="customer-floor-plan"><div className="floor-plan-title"><span><Armchair/> Sơ đồ một tầng</span><b>Đã chọn {capacity}/{form.partySize} ghế</b></div>{!form.reservationDate?<p>Chọn ngày và giờ để xem bàn trống.</p>:<div className="selectable-map">{tables.map(table=><button type="button" key={table.id} onClick={()=>toggleTable(table.id)} className={`${selectedTables.includes(table.id)?'selected':''} ${table.shape.toLowerCase()}`} style={{left:`${table.layoutX}%`,top:`${table.layoutY}%`}}><b>{table.code}</b><small>{table.seats} ghế</small></button>)}{!tables.length&&<p>Không còn bàn phù hợp trong khung giờ này.</p>}</div>}</div>
    <div className="preorder-section"><h2>Chọn món trước</h2><div className="preorder-total"><ShoppingBasket/><span><b>{selected.length} món</b><small>Tạm tính {total.toLocaleString('vi-VN')} ₫</small></span></div><div className="preorder-grid">{menu.map(item=><article className={qty[item.id]?'selected':''} key={item.id}><img src={item.imageUrl} alt={item.name}/><div><span>{item.category}</span><h3>{item.name}</h3><b>{Number(item.price).toLocaleString('vi-VN')} ₫</b></div><div className="quantity"><button type="button" onClick={()=>setQty({...qty,[item.id]:Math.max(0,(qty[item.id]||0)-1)})}><Minus/></button><strong>{qty[item.id]||0}</strong><button type="button" onClick={()=>setQty({...qty,[item.id]:Math.min(20,(qty[item.id]||0)+1)})}><Plus/></button></div></article>)}</div></div><div className="deposit-preview"><span>Tiền cọc dự kiến</span><b>{deposit.toLocaleString('vi-VN')} ₫</b><small>{selected.length?'10% tổng tiền món':'200.000 ₫ × số khách'}</small></div>{error&&<p className="error">{error}</p>}<button disabled={loading} className="btn btn-green">{loading?'Đang giữ bàn...':'Giữ bàn và thanh toán cọc'}</button></form></section>
}
