import{Check,ChefHat,Minus,Plus,Search,Send,ShoppingBasket,UtensilsCrossed,X}from'lucide-react';
import{useEffect,useMemo,useState}from'react';
import{api}from'../api';
import type{DiningOrder,MenuItem,Reservation}from'../types';

const statusLabel:Record<DiningOrder['status'],string>={SUBMITTED:'Đã gửi bếp',PREPARING:'Đang chế biến',READY:'Sẵn sàng',SERVED:'Đã phục vụ',CANCELLED:'Đã hủy'};
export default function ServicePage(){
  const[reservations,setReservations]=useState<Reservation[]>([]);const[menu,setMenu]=useState<MenuItem[]>([]);const[orders,setOrders]=useState<Record<number,DiningOrder[]>>({});
  const[selected,setSelected]=useState<Reservation>();const[quantities,setQuantities]=useState<Record<number,number>>({});const[note,setNote]=useState('');const[search,setSearch]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  async function load(){try{const[all,dishes]=await Promise.all([api.staffReservations(),api.menu()]);const active=all.filter(row=>row.status==='CHECKED_IN'&&row.serviceSessionId);setReservations(active);setMenu(dishes);const pairs=await Promise.all(active.map(async row=>[row.id,await api.sessionOrders(row.serviceSessionId!)] as const));setOrders(Object.fromEntries(pairs));setError('')}catch(err){setError(err instanceof Error?err.message:'Không tải được dữ liệu phục vụ')}}
  useEffect(()=>{void load()},[]);
  const filtered=useMemo(()=>menu.filter(item=>item.name.toLowerCase().includes(search.toLowerCase())||item.category.toLowerCase().includes(search.toLowerCase())),[menu,search]);
  function change(id:number,delta:number){setQuantities(value=>({...value,[id]:Math.max(0,(value[id]||0)+delta)}))}
  async function submit(){if(!selected?.serviceSessionId)return;const items=Object.entries(quantities).filter(([,quantity])=>quantity>0).map(([menuItemId,quantity])=>({menuItemId:Number(menuItemId),quantity}));if(!items.length){setError('Hãy chọn ít nhất một món');return}setBusy(true);try{await api.createOrder(selected.serviceSessionId,{items,note});setSelected(undefined);setQuantities({});setNote('');await load()}catch(err){setError(err instanceof Error?err.message:'Không gửi được phiếu món')}finally{setBusy(false)}}
  async function orderAction(operation:()=>Promise<unknown>){setBusy(true);try{await operation();await load()}catch(err){setError(err instanceof Error?err.message:'Không cập nhật được phiếu món')}finally{setBusy(false)}}
  return <section className="page-section container service-page"><p className="eyebrow dark">PHỤC VỤ TẠI BÀN</p><h1>Gọi món & theo dõi bếp</h1><p className="page-lead">Chọn bàn đang phục vụ để tạo phiếu món mới; trạng thái được cập nhật xuyên suốt giữa phục vụ và bếp.</p>{error&&<p className="error">{error}</p>}
    <div className="service-cards">{reservations.map(row=><article key={row.id}><header><span><UtensilsCrossed/><b>{row.assignedTables.map(table=>table.code).join(', ')}</b></span><small>{row.customerName} • {row.partySize} khách</small></header><div className="ticket-list">{(orders[row.id]||[]).map(order=><div className={`mini-ticket ${order.status.toLowerCase()}`} key={order.id}><span><b>Phiếu #{order.id} {order.source==='PREORDER'&&<em>Đặt trước</em>}</b><small>{order.items.map(item=>`${item.quantity}× ${item.itemName}`).join(' • ')}</small></span><i>{statusLabel[order.status]}</i>{order.status==='READY'&&<button disabled={busy} onClick={()=>orderAction(()=>api.serveOrder(order.id))}><Check/> Đã mang món</button>}{order.status==='SUBMITTED'&&<button className="cancel-ticket" disabled={busy} onClick={()=>orderAction(()=>api.cancelOrder(order.id))}>Hủy</button>}</div>)}{!(orders[row.id]||[]).length&&<p>Chưa có phiếu gọi món.</p>}</div><div className="service-card-actions"><button className="btn btn-green" onClick={()=>{setSelected(row);setQuantities({});setError('')}}><Plus/> Gọi thêm món</button><button className="btn complete-table" disabled={busy||(orders[row.id]||[]).some(order=>['SUBMITTED','PREPARING','READY'].includes(order.status))} onClick={()=>orderAction(()=>api.completeService(row.id))}><Check/> Hoàn tất lượt khách</button></div>{(orders[row.id]||[]).some(order=>['SUBMITTED','PREPARING','READY'].includes(order.status))&&<p className="service-block-note">Hãy đợi bếp hoàn thành và bấm “Đã mang món” cho tất cả phiếu.</p>}</article>)}{!reservations.length&&<div className="service-empty"><ChefHat/><h2>Chưa có bàn đang phục vụ</h2><p>Khách cần được xác nhận, xếp bàn và check-in trước khi gọi món.</p></div>}</div>
    {selected&&<div className="order-modal"><div className="order-modal-head"><div><p className="eyebrow dark">TẠO PHIẾU GỌI MÓN</p><h2>{selected.assignedTables.map(table=>table.code).join(', ')} — {selected.customerName}</h2></div><button aria-label="Đóng phiếu gọi món" onClick={()=>setSelected(undefined)}><X/></button></div><div className="order-search"><Search/><input placeholder="Tìm món..." value={search} onChange={event=>setSearch(event.target.value)}/></div><div className="order-menu">{filtered.map(item=><article className={quantities[item.id]?'selected':''} key={item.id}><img src={item.imageUrl} alt=""/><span><small>{item.category}</small><b>{item.name}</b><i>{Number(item.price).toLocaleString('vi-VN')}đ</i></span><div><button aria-label={`Giảm ${item.name}`} onClick={()=>change(item.id,-1)}><Minus/></button><strong>{quantities[item.id]||0}</strong><button aria-label={`Thêm ${item.name}`} onClick={()=>change(item.id,1)}><Plus/></button></div></article>)}</div><textarea placeholder="Ghi chú cho bếp: ít cay, không hành..." value={note} onChange={event=>setNote(event.target.value)}/><div className="order-total"><span><ShoppingBasket/> {Object.values(quantities).reduce((sum,value)=>sum+value,0)} món</span><b>{menu.reduce((sum,item)=>sum+(quantities[item.id]||0)*Number(item.price),0).toLocaleString('vi-VN')}đ</b><button disabled={busy} onClick={submit}><Send/> Gửi phiếu xuống bếp</button></div></div>}
  </section>
}
