import type {AuthUser,AvailableTable,Checkout,DiningOrder,GuestTable,MenuItem,Notification,OperationalTimeout,OperationsReport,PayPalConfig,PayPalOrder,Reservation,ReservationStatusEvent,RestaurantTable,StaffShift,TableOverview,TableRequest,TimeoutPolicy,UserStats,UserSummary,WaiterAssignment,WaiterAssignmentEvent,WaiterSummary,WalkInMetrics,WalkInVisit} from './types'
const BASE=import.meta.env.VITE_API_URL||'/api/v1'
const token=()=>{try{return JSON.parse(localStorage.getItem('restaurant_auth')||'null')?.accessToken}catch{return null}}
async function request<T>(path:string,options?:RequestInit):Promise<T>{const auth=token();const response=await fetch(`${BASE}${path}`,{headers:{'Content-Type':'application/json',...(auth?{Authorization:`Bearer ${auth}`}:{}) ,...options?.headers},...options});const text=await response.text();let data:null|Record<string,unknown>=null;try{data=text?JSON.parse(text):null}catch{data=null}if(!response.ok)throw new Error(typeof data?.message==='string'?data.message:(response.status===401||response.status===403?'Phiên đăng nhập không hợp lệ':'Có lỗi xảy ra'));return data as T}
export const api={
  login:(email:string,password:string)=>request<AuthUser>('/auth/login',{method:'POST',body:JSON.stringify({email,password})}),
  register:(body:unknown)=>request<AuthUser>('/auth/register',{method:'POST',body:JSON.stringify(body)}),
  adminUserStats:()=>request<UserStats>('/admin/users/stats'),
  adminOperationsReport:()=>request<OperationsReport>('/admin/reports/operations'),
  adminUsers:()=>request<UserSummary[]>('/admin/users'),
  menu:()=>request<MenuItem[]>('/menu/items'),
  staffMenu:()=>request<MenuItem[]>('/staff/menu/items'),
  createMenuItem:(body:unknown)=>request<MenuItem>('/staff/menu/items',{method:'POST',body:JSON.stringify(body)}),
  updateMenuItem:(id:number,body:unknown)=>request<MenuItem>(`/staff/menu/items/${id}`,{method:'PUT',body:JSON.stringify(body)}),
  setMenuAvailability:(id:number,available:boolean)=>request<MenuItem>(`/staff/menu/items/${id}/availability`,{method:'PATCH',body:JSON.stringify({available})}),
  createReservation:(body:unknown)=>request<Reservation>('/reservations',{method:'POST',body:JSON.stringify(body)}),
  availableTables:(date:string,time:string,durationMinutes:number,partySize:number)=>request<AvailableTable[]>(`/reservations/available-tables?date=${date}&time=${time}&durationMinutes=${durationMinutes}&partySize=${partySize}`),
  lookup:(code:string,phone:string)=>request<Reservation>(`/reservations/lookup?code=${encodeURIComponent(code)}&phone=${encodeURIComponent(phone)}`),
  depositPayPalConfig:(code:string)=>request<PayPalConfig>(`/reservations/${encodeURIComponent(code)}/deposit/paypal/config`),
  createDepositPayPal:(code:string,phone:string)=>request<PayPalOrder>(`/reservations/${encodeURIComponent(code)}/deposit/paypal/orders`,{method:'POST',body:JSON.stringify({phone})}),
  captureDepositPayPal:(code:string,phone:string,orderId:string)=>request<unknown>(`/reservations/${encodeURIComponent(code)}/deposit/paypal/orders/capture`,{method:'POST',body:JSON.stringify({phone,orderId})}),
  staffReservations:()=>request<Reservation[]>('/staff/reservations'),
  staffServiceReservations:()=>request<Reservation[]>('/staff/service-reservations'),
  updateStatus:(id:number,status:string,reason?:string)=>request<Reservation>(`/staff/reservations/${id}/status`,{method:'PATCH',body:JSON.stringify({status,reason})}),
  reservationStatusHistory:(id:number)=>request<ReservationStatusEvent[]>(`/staff/reservations/${id}/history`),
  confirmPreOrder:(id:number)=>request<Reservation>(`/staff/reservations/${id}/preorder/confirm`,{method:'POST'}),
  assignTables:(id:number,tableIds:number[])=>request<Reservation>(`/staff/reservations/${id}/tables`,{method:'PUT',body:JSON.stringify({tableIds})}),
  checkIn:(id:number)=>request<Reservation>(`/staff/reservations/${id}/check-in`,{method:'POST'}),
  completeService:(id:number)=>request<Reservation>(`/staff/reservations/${id}/complete`,{method:'POST'}),
  tables:()=>request<RestaurantTable[]>('/staff/tables'),
  tableOverview:()=>request<TableOverview[]>('/staff/tables/overview'),
  waiters:()=>request<WaiterSummary[]>('/staff/service-sessions/waiters'),
  waiterAssignmentHistory:(sessionId?:number)=>request<WaiterAssignmentEvent[]>(`/staff/service-sessions/waiter-history${sessionId?`?sessionId=${sessionId}`:''}`),
  claimServiceSession:(sessionId:number,reason='Nhân viên tự nhận bàn')=>request<WaiterAssignment>(`/staff/service-sessions/${sessionId}/claim`,{method:'POST',body:JSON.stringify({reason})}),
  assignServiceSession:(sessionId:number,staffId:number,reason?:string)=>request<WaiterAssignment>(`/staff/service-sessions/${sessionId}/waiter`,{method:'PUT',body:JSON.stringify({staffId,reason})}),
  unassignServiceSession:(sessionId:number,reason:string)=>request<WaiterAssignment>(`/staff/service-sessions/${sessionId}/waiter`,{method:'DELETE',body:JSON.stringify({reason})}),
  adminShifts:()=>request<StaffShift[]>('/admin/shifts'),
  createShift:(body:{staffId:number;startsAt:string;endsAt:string})=>request<StaffShift>('/admin/shifts',{method:'POST',body:JSON.stringify(body)}),
  startShift:(id:number)=>request<StaffShift>(`/admin/shifts/${id}/start`,{method:'POST'}),
  completeShift:(id:number)=>request<StaffShift>(`/admin/shifts/${id}/complete`,{method:'POST'}),
  cancelShift:(id:number)=>request<StaffShift>(`/admin/shifts/${id}/cancel`,{method:'POST'}),
  updateTableStatus:(id:number,status:string)=>request<RestaurantTable>(`/staff/tables/${id}/status`,{method:'PATCH',body:JSON.stringify({status})}),
  createTable:(body:unknown)=>request<RestaurantTable>('/staff/tables',{method:'POST',body:JSON.stringify(body)}),
  sessionOrders:(sessionId:number)=>request<DiningOrder[]>(`/staff/service-sessions/${sessionId}/orders`),
  createOrder:(sessionId:number,body:unknown)=>request<DiningOrder>(`/staff/service-sessions/${sessionId}/orders`,{method:'POST',body:JSON.stringify(body)}),
  serveOrder:(id:number)=>request<DiningOrder>(`/staff/orders/${id}/served`,{method:'PATCH'}),
  cancelOrder:(id:number)=>request<DiningOrder>(`/staff/orders/${id}/cancel`,{method:'PATCH'}),
  kitchenOrders:()=>request<DiningOrder[]>('/kitchen/orders'),
  updateKitchenOrder:(id:number,status:'PREPARING'|'READY')=>request<DiningOrder>(`/kitchen/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status})}),
  updateKitchenItem:(id:number,body:unknown)=>request<DiningOrder>(`/kitchen/orders/items/${id}/status`,{method:'PATCH',body:JSON.stringify(body)}),
  serveOrderItem:(id:number)=>request<DiningOrder>(`/staff/order-items/${id}/served`,{method:'PATCH'}),
  notifications:()=>request<Notification[]>('/staff/notifications'),
  readNotification:(id:number)=>request<void>(`/staff/notifications/${id}/read`,{method:'PATCH'}),
  tableRequests:()=>request<TableRequest[]>('/staff/table-requests'),
  updateTableRequest:(id:number,status:string)=>request<TableRequest>(`/staff/table-requests/${id}`,{method:'PATCH',body:JSON.stringify({status})}),
  timeouts:()=>request<OperationalTimeout[]>('/staff/timeouts'),
  timeoutPolicy:()=>request<TimeoutPolicy>('/staff/timeouts/policy'),
  resolveTimeout:(id:number,note='Đã xử lý')=>request<OperationalTimeout>(`/staff/timeouts/${id}/resolve`,{method:'PATCH',body:JSON.stringify({note})}),
  assignTimeout:(id:number,assignee:string,note='')=>request<OperationalTimeout>(`/staff/timeouts/${id}/assign`,{method:'PATCH',body:JSON.stringify({assignee,note})}),
  acknowledgeTimeout:(id:number)=>request<OperationalTimeout>(`/staff/timeouts/${id}/acknowledge`,{method:'PATCH'}),
  walkIns:()=>request<WalkInVisit[]>('/staff/walk-ins'),
  walkInMetrics:()=>request<WalkInMetrics>('/staff/walk-ins/metrics'),
  createWalkIn:(body:unknown)=>request<WalkInVisit>('/staff/walk-ins',{method:'POST',body:JSON.stringify(body)}),
  createWalkInDemo:()=>request<{created:boolean;visits:number;message:string}>('/staff/walk-ins/demo-scenario',{method:'POST'}),
  reviseWalkInQuote:(id:number,quotedWaitMinutes:number,note='')=>request<WalkInVisit>(`/staff/walk-ins/${id}/quote`,{method:'PATCH',body:JSON.stringify({quotedWaitMinutes,note})}),
  offerWalkInTable:(id:number,tableId:number,note='')=>request<WalkInVisit>(`/staff/walk-ins/${id}/offer`,{method:'POST',body:JSON.stringify({tableId,note})}),
  walkInAction:(id:number,action:string,body:unknown={})=>request<WalkInVisit>(`/staff/walk-ins/${id}/${action}`,{method:'POST',body:JSON.stringify(body)}),
  exitWalkIn:(id:number,status:string,note='')=>request<WalkInVisit>(`/staff/walk-ins/${id}/exit/${status}`,{method:'POST',body:JSON.stringify({note})}),
  guestTable:(token:string)=>request<GuestTable>(`/table-guest/${encodeURIComponent(token)}`),
  createTableRequest:(token:string,type:string,note:string)=>request<TableRequest>(`/table-guest/${encodeURIComponent(token)}/requests`,{method:'POST',body:JSON.stringify({type,note})}),
  checkouts:()=>request<Checkout[]>('/staff/checkouts'),
  paypalConfig:()=>request<PayPalConfig>('/staff/checkouts/paypal/config'),
  createPayPalOrder:(sessionId:number,discountAmount:number)=>request<PayPalOrder>(`/staff/checkouts/${sessionId}/paypal/orders`,{method:'POST',body:JSON.stringify({discountAmount})}),
  capturePayPalOrder:(sessionId:number,orderId:string,discountAmount:number)=>request<Checkout>(`/staff/checkouts/${sessionId}/paypal/orders/${encodeURIComponent(orderId)}/capture`,{method:'POST',body:JSON.stringify({discountAmount})})
}
