import {Route,Routes} from 'react-router-dom'
import Header from './components/Header'
import Footer from './components/Footer'
import HomePage from './pages/HomePage'
import MenuPage from './pages/MenuPage'
import ReservationPage from './pages/ReservationPage'
import LookupPage from './pages/LookupPage'
import DashboardPage from './pages/DashboardPage'
import LoginPage from './pages/LoginPage'
import TablesPage from './pages/TablesPage'
import ProtectedRoute from './components/ProtectedRoute'
export default function App(){return <><Header/><main><Routes><Route path="/" element={<HomePage/>}/><Route path="/thuc-don" element={<MenuPage/>}/><Route path="/dat-ban" element={<ReservationPage/>}/><Route path="/tra-cuu" element={<LookupPage/>}/><Route path="/dang-nhap" element={<LoginPage/>}/><Route path="/staff" element={<ProtectedRoute><DashboardPage/></ProtectedRoute>}/><Route path="/staff/ban" element={<ProtectedRoute><TablesPage/></ProtectedRoute>}/></Routes></main><Footer/></>}
