import {Route,Routes} from 'react-router-dom'
import Header from './components/Header'
import Footer from './components/Footer'
import HomePage from './pages/HomePage'
import MenuPage from './pages/MenuPage'
import ReservationPage from './pages/ReservationPage'
import LookupPage from './pages/LookupPage'
import DashboardPage from './pages/DashboardPage'
import LoginPage from './pages/LoginPage'
import TablesPage from './pages/TablesPage'
import ProtectedRoute from './components/ProtectedRoute'
import CustomerPage from './pages/CustomerPage'
import AdminDashboardPage from './pages/AdminDashboardPage'
import AdminUsersPage from './pages/AdminUsersPage'
const staffRoles=['ADMIN','STAFF'] as const;
export default function App(){return <><Header/><main><Routes><Route path="/" element={<HomePage/>}/><Route path="/thuc-don" element={<MenuPage/>}/><Route path="/dat-ban" element={<ReservationPage/>}/><Route path="/tra-cuu" element={<LookupPage/>}/><Route path="/dang-nhap" element={<LoginPage/>}/><Route path="/tai-khoan" element={<ProtectedRoute roles={['CUSTOMER']}><CustomerPage/></ProtectedRoute>}/><Route path="/admin" element={<ProtectedRoute roles={['ADMIN']}><AdminDashboardPage/></ProtectedRoute>}/><Route path="/admin/tai-khoan" element={<ProtectedRoute roles={['ADMIN']}><AdminUsersPage/></ProtectedRoute>}/><Route path="/staff" element={<ProtectedRoute roles={[...staffRoles]}><DashboardPage/></ProtectedRoute>}/><Route path="/staff/ban" element={<ProtectedRoute roles={[...staffRoles]}><TablesPage/></ProtectedRoute>}/></Routes></main><Footer/></>}
