import{Route,Routes,useLocation}from'react-router-dom';import Header from'./components/Header';import Footer from'./components/Footer';import WorkspaceNav from'./components/WorkspaceNav';import HomePage from'./pages/HomePage';import MenuPage from'./pages/MenuPage';import ReservationPage from'./pages/ReservationPage';import LookupPage from'./pages/LookupPage';import DashboardPage from'./pages/DashboardPage';import LoginPage from'./pages/LoginPage';import RegisterPage from'./pages/RegisterPage';import TablesPage from'./pages/TablesPage';import ProtectedRoute from'./components/ProtectedRoute';import CustomerPage from'./pages/CustomerPage';import AdminDashboardPage from'./pages/AdminDashboardPage';import AdminUsersPage from'./pages/AdminUsersPage';import AdminShiftsPage from'./pages/AdminShiftsPage';import ServicePage from'./pages/ServicePage';import KitchenPage from'./pages/KitchenPage';import CashierPage from'./pages/CashierPage';import MenuManagementPage from'./pages/MenuManagementPage';
import TableGuestPage from'./pages/TableGuestPage';
import WalkInPage from'./pages/WalkInPage';
const staffRoles=['ADMIN','STAFF']as const;
export default function App(){const{pathname}=useLocation();const workspace=pathname.startsWith('/admin')||pathname.startsWith('/staff')||pathname==='/bep';const tableGuest=pathname.startsWith('/ban/');return <>{!tableGuest&&<Header/>}{workspace&&<WorkspaceNav/>}<main className={workspace?'workspace-main':tableGuest?'table-guest-main':''}><Routes>
 <Route path="/" element={<HomePage/>}/><Route path="/thuc-don" element={<MenuPage/>}/><Route path="/dat-ban" element={<ReservationPage/>}/><Route path="/tra-cuu" element={<LookupPage/>}/><Route path="/dang-nhap" element={<LoginPage/>}/><Route path="/dang-ky" element={<RegisterPage/>}/>
 <Route path="/ban/:token" element={<TableGuestPage/>}/>
 <Route path="/tai-khoan" element={<ProtectedRoute roles={['CUSTOMER']}><CustomerPage/></ProtectedRoute>}/><Route path="/admin" element={<ProtectedRoute roles={['ADMIN']}><AdminDashboardPage/></ProtectedRoute>}/><Route path="/admin/tai-khoan" element={<ProtectedRoute roles={['ADMIN']}><AdminUsersPage/></ProtectedRoute>}/><Route path="/admin/ca-lam-viec" element={<ProtectedRoute roles={['ADMIN']}><AdminShiftsPage/></ProtectedRoute>}/>
 <Route path="/staff" element={<ProtectedRoute roles={[...staffRoles]}><DashboardPage/></ProtectedRoute>}/><Route path="/staff/walk-in" element={<ProtectedRoute roles={[...staffRoles]}><WalkInPage/></ProtectedRoute>}/><Route path="/staff/phuc-vu" element={<ProtectedRoute roles={[...staffRoles]}><ServicePage/></ProtectedRoute>}/><Route path="/staff/ban" element={<ProtectedRoute roles={[...staffRoles]}><TablesPage/></ProtectedRoute>}/><Route path="/staff/thuc-don" element={<ProtectedRoute roles={[...staffRoles]}><MenuManagementPage/></ProtectedRoute>}/><Route path="/staff/thanh-toan" element={<ProtectedRoute roles={[...staffRoles]}><CashierPage/></ProtectedRoute>}/><Route path="/bep" element={<ProtectedRoute roles={['ADMIN','KITCHEN']}><KitchenPage/></ProtectedRoute>}/>
</Routes></main>{!workspace&&!tableGuest&&<Footer/>}</>}
